plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

# Metrics
Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Metrics/AbcSize:
  Max: 20

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

Layout/EndOfLine:
  Enabled: false

# Rails
Rails/I18nLocaleTexts:
  Enabled: false

Rails/Exit:
  Exclude:
    - 'spec/**/*'
